apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: docker.io/hhayakaw/cowweb
    workspace: .
    docker:
      dockerfilePath: ./build_local/Dockerfile
  local:
    skipPush: true
deploy:
  kubectl:
    manifests:
      - ./build_local/cowweb*.yaml
profiles:
  - name: release
    build:
      artifacts:
      - imageName: docker.io/hhayakaw/cowweb
        workspace: .
        docker:
          dockerfilePath: ./build_release/Dockerfile
      local:
        skipPush: false
      tagPolicy:
        gitCommit: {}
    deploy:
      kubectl:
        manifests:
          - ./build_release/cowweb*.yaml
