apiVersion: v1
kind: Service
metadata:
  name: cowweb
  namespace: cowweb-local-dev
spec:
  type: NodePort
  selector:
    app: cowweb
  ports:
  - name: http
    port: 8080
    nodePort: 30080
  - name: debug
    port: 8081
    nodePort: 30081
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cowweb
  namespace: cowweb-local-dev
  labels:
    app: cowweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cowweb
    spec:
      containers:
      - name: cowweb
        image: docker.io/hhayakaw/cowweb
        ports:
        - name: api
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /cowsay/ping
            port: api
          initialDelaySeconds: 15
          periodSeconds: 20
